#!/bin/sh
default_stages: [commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev:  v4.3.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-toml
        stages: [push]
    -   id: check-yaml
        stages: [push]
    -   id: end-of-file-fixer
        stages: [push]
    -   id: trailing-whitespace
        stages: [push]
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        name: Running black formatter and linter
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
    -   id: flake8
        name: Running flake8 linter
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: Running isort
