default_stages: [commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev:  v4.3.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-toml
        stages: [push]
    -   id: check-yaml
        stages: [push]
    -   id: end-of-file-fixer
        stages: [push]
    -   id: trailing-whitespace
        stages: [push]
-   repo: local
    hooks:
    -   id: black
        name: Running black
        entry: python3 -m black .
        # Black does not work with language as python
        language: system
        types:
          - python
    -   id: flake8
        name: Running flake8
        entry: python3 -m flake8 .
        language: system
        pass_filenames: false
        types:
          - python
    -   id: isort
        name: Running isort
        entry: python3 -m isort .
        language: system
        types:
          - python
    -   id: lizard
        name: Running lizard
        entry: python3 -m lizard
        # Max 8 arguments allowed, show only warnings, sort by CCN, exclude .venv
        args: ["--CCN", "8", "-a", "8", "-w", "-s", "cyclomatic_complexity", "-x", ".\\.venv\\*"]
        language: system
        types:
          - python
