services:
  app:
    depends_on:
      - db
      - pgadmin
    container_name: splitwise
    build:
      context: .
    command: bash -c "alembic upgrade head && fastapi dev --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/app/
    restart: always

  db:
    container_name: pgdb
    image: postgres:13
    ports:
      - 5432:5432
    env_file:
      - ./db/local.env
    tty: true

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    depends_on:
      - db
