services:
  app:
    depends_on:
      - db
    container_name: splitwise
    build:
      context: .
    command: bash -c "alembic upgrade head && fastapi dev --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/app/
    restart: always

  db:
    container_name: pgdb
    image: postgres:13
    ports:
      - 5432:5432
    env_file:
      - ./db/local.env
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    tty: true

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
      - app
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80

  superset:
    build:
      context: .
      dockerfile: ./superset/Dockerfile
    container_name: superset
    depends_on:
      - db
      - app
    env_file:
    - .env
    ports:
      - '8088:$SUPERSET_PORT'

  superset-create-dashboard:
    build:
      context: .
      dockerfile: ./superset/dashboard/Dockerfile
    container_name: superset-create-dashboard
    env_file:
    - .env
    depends_on:
      superset:
        condition: service_healthy
      db:
        condition: service_started
    volumes:
      - ./superset/dashboard/scripts:/scripts
    tty: true

volumes:
      postgres_data:
