"""Update expense and group id to BigInt

Revision ID: 24824680577a
Revises: fa3fd2c57ff9
Create Date: 2024-08-04 17:59:55.473639

"""

from __future__ import annotations

from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24824680577a"
down_revision: Union[str, None] = "fa3fd2c57ff9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("expenses", "expense_id", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=True)
    op.alter_column("expenses", "group_id", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("expenses", "group_id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=True)
    op.alter_column("expenses", "expense_id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=True)
    # ### end Alembic commands ###
