name: Code quality check
on: [push, pull_request]
jobs:
   lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python_version: '3.12'

      - name: Install pip and dependencies
        run: |
          PACKAGE_LINE=$(grep '^ruff' requirements.txt)
          pip install "$PACKAGE_LINE"

      - name: Lint code
        run: ruff check --output-format=github .
